services:
  nextjs: # Nom de service unique
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        # Crucial : On pointe vers l'URL de l'API de dev !
        - NEXT_PUBLIC_API_BASE=https://phobee.net/api
    container_name: phobee_nextjs_dev # Nom de conteneur unique
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Tu peux ajouter une variable pour afficher un bandeau "STAGING" sur ton site
      - NEXT_PUBLIC_APP_ENV=staging
    env_file:
      - ./web/.env # Utilise un fichier env spécifique à la dev
    networks:
      - phobee_shared_net

networks:
  phobee_shared_net:
    external: true
